import { afterEach, describe, expect, it } from "bun:test";
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fixtureEffects } from "../../../src/entry/tui/fixtures.ts";
import { applyStep, STORIES } from "../../../src/entry/tui/stories.ts";
import { App } from "../../../src/entry/tui/views/app.tsx";
import { snapshotEnv, withHome } from "../../helpers.ts";
import { harness, PLAIN, UI } from "./harness.tsx";

afterEach(snapshotEnv());

/** Spec §11.6: every screen at three sizes, in Unicode and plain. */
const SIZES = [
  [80, 24],
  [100, 30],
  [120, 40],
] as const;
const FRAMES_DOC = join(import.meta.dir, "..", "..", "..", "docs", "tui-frames.md");

async function frame(
  story: (typeof STORIES)[number],
  width: number,
  height: number,
  plain: boolean,
): Promise<string> {
  withHome();
  const h = await harness(<App />, {
    effects: fixtureEffects(story.fixtures),
    ui: plain ? PLAIN : UI,
    width,
    height,
  });
  for (const step of story.steps) await h.run(() => applyStep(step, h.app(), h.keymap()));
  await h.advance(0);
  await h.advance(0);
  const f = h.s.frame().replace(/ +$/gm, "");
  await h.s.close();
  return f;
}

const cases = STORIES.flatMap((story) =>
  SIZES.flatMap(([w, hgt]) => [false, true].map((plain) => ({ story, w, h: hgt, plain }))),
);
const frames = new Map<string, string>();
const keyOf = (c: (typeof cases)[number]) => `${c.story.name} ${c.w}x${c.h}${c.plain ? " plain" : ""}`;

describe("frames", () => {
  it.each(cases.map((c) => [keyOf(c), c] as const))("%s", async (_k, c) => {
    const f = await frame(c.story, c.w, c.h, c.plain);
    frames.set(keyOf(c), f);
    const lines = f.split("\n");
    for (const l of lines) expect(Bun.stringWidth(l)).toBeLessThanOrEqual(c.w);
    // the footer is on the last row, row h: the keys are always in view
    expect(lines).toHaveLength(c.h + 1);
    expect(lines[c.h - 1]).toMatch(/choose|commands/);
    if (c.plain) expect(f).toMatch(/^[\x20-\x7e\n]*$/);
    expect(f).toMatchSnapshot();
  });

  it("docs/tui-frames.md is the 80×24 frames, generated (CATHERD_WRITE_FRAMES=1 rewrites it)", () => {
    const doc = [
      "# catherd TUI frames",
      "",
      "Generated by `CATHERD_WRITE_FRAMES=1 bun test test/entry/tui/frames.test.tsx` from the storybook's",
      "stories (`src/entry/tui/stories.ts`) on the fixtures; do not edit by hand.",
      "",
      ...STORIES.flatMap((s) => [`## ${s.title}`, "", "```", frames.get(`${s.name} 80x24`) ?? "", "```", ""]),
    ].join("\n");
    if (process.env.CATHERD_WRITE_FRAMES) writeFileSync(FRAMES_DOC, doc);
    expect(readFileSync(FRAMES_DOC, "utf8")).toBe(doc);
  });
});
